# Generated by Django 4.2.27 on 2026-03-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('publication_year', models.IntegerField()),
            ],
            options={
                'permissions': [('can_view', 'Can view'), ('can_create', 'Can create'), ('can_edit', 'Can edit'), ('can_delete', 'Can delete')],
            },
        ),
    ]
